
version: '3'

services:
    back-end:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: back-end
        restart: always
        depends_on:
        - "mongodb"
        volumes:
            - ./:/backend
            - /backend/node_modules
        ports:
            - '5000:5000'
        networks:
        - shared_network
    mongodb:
      image : mongo
      container_name: mongodb
      ports:
      - 27017:27017
      restart: unless-stopped
      networks:
        - shared_network

networks:
  shared_network:
    driver: bridge